Adding optional error handler parameter to DFUFirmware initializers.
NordicSemiconductor/IOS-DFU-Library pull request #463
Opened 2021-10-19 10:20 UTC by appfactoryCo

Hello there,

Thank you for creating this useful library. 

I was trying to create a firmware file by passing a url. I noticed that I didn't get enough information about the kind of error that happened when using the DFUFirmware initializer. 
For example, when I passed it a url to a zip file like this:
```swift
let firmware = DFUFirmware(urlToZipFile: firmwareUrl)
```

 Then, I found this error in the logs:
```
Error while creating ZIP stream: The operation couldn’t be completed. (NordicDFU.DFUStreamZipError error 0.)
```

I had no idea what that meant, and there was no initializer that would give my app an error. So, I added errorHandler parameter to the DFUFirmware initializers to get some errors back to my app:
```swift
@objc convenience public init?(urlToZipFile: URL, errorHandler: ((String) -> ())?)
```

For example, now I can do something like this:
```swift
let firmware = DFUFirmware(urlToZipFile: firmwareUrl, errorHandler: { [weak self]
                    errorMsg in
                    DispatchQueue.main.async { // Handle creating firmware errors in main thread
                        self?.raiseAlert(title: "Sorry", message: errorMsg)
                    }
                })
```
or
```swift
let firmware = DFUFirmware(urlToZipFile: firmwareUrl, errorHandler: nil)
```

Doing so helped me figure out what the error was. It was "No manifest file found," and now I can let the app display this error back to the user.

I hope this little contribution is useful.

Thanks a lot.

2021-10-19 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NordicSemiconductor/IOS-DFU-Library?pullRequest=463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NordicSemiconductor/IOS-DFU-Library?pullRequest=463) before we can accept your contribution.<br/><hr/>**Badr Bujbara** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicSemiconductor/IOS-DFU-Library?pullRequest=463) it.</sub>

2022-05-31 08:30 UTC, philips77 requested changes
Hi,
Sorry for looking into the PR after such a long time, but I was buried with other tasks. I left few comments.
In general, I like the error handler idea. I would, however, return the actually error, not a string.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc convenience public init?(urlToZipFile: URL, errorHandler: ((String) -> ())?) {
The error handler should be `nil` by default, not only optional.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc public init?(urlToZipFile: URL, type: DFUFirmwareType, errorHandler: ((String) -> ())?) {
The error handler could be `nil` by default, not only optional.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +            errorHandler?("The selected file \(fileName ?? "") is not a ZIP file.")
This produces 2 spaces between "file" and "is" if the `fileName` is `nil`.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +            NSLog("Error while creating ZIP stream: ERROR >>> \(error)  ERR DESC >>> \(error.localizedDescription)")
Actually, the error should extend `LocalizedError` like here:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/0f25a7127d1581d1f81e026742257dc08fa251f7/nRFMeshProvision/Classes/MeshNetworkError.swift#L88
instead of using `error.localizedDescription`.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc convenience public init?(zipFile: Data, errorHandler: ((String) -> ())?) {
`nil` by default.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc public init?(zipFile: Data, type: DFUFirmwareType, errorHandler: ((String) -> ())?) {
`nil` by default.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +                       errorHandler: ((String) -> ())?) {
`nil` by default.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
>              NSLog("\(fileName!) is not a BIN or HEX file")
Actually, with those new error handlers we may no longer need logging to `NSLog` anywhere in the file. This may be done by the app.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> -
Please, don't change structure. We sometimes add empty lines or spaces to make the code more readable, at least in our opinion.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc public init?(hexFile: Data, datFile: Data?, type: DFUFirmwareType, errorHandler: ((String) -> ())?) {
`nil` by default.

2022-05-31 08:30 UTC, philips77 commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc convenience public init?(urlToZipFile: URL, errorHandler: ((String) -> ())?) {
Also, the error handler should return the error, not a String.

2022-05-31 08:40 UTC, dinesharjani commented on iOSDFULibrary/Classes/Implementation/Firmware/DFUFirmware.swift
> +    @objc public init?(urlToZipFile: URL, type: DFUFirmwareType, errorHandler: ((String) -> ())?) {
Just to add a bit more to the suggestions made by @philips77 , we want to make changes that don't break compatibility with existing code as much as we can avoid doing so. That is our reasoning.

2022-05-31 08:48 UTC, philips77 commented
I think we'll close this PR and try coming up with something similar to solve your problem. The `init` may throw an error instead of returning `nil`.

2022-06-30 11:38 UTC, philips77 commented
Closed with #486.

2022-06-30 11:38 UTC, closed without merging